---

- hosts: all
  remote_user: root
  # become: true
  # become_user: root
  gather_facts: false
  roles:
#    - { role: java }
    - { role: tomcat }
#    - { role: mysql}
    - { role: java_app_deploy }
#    - { role: nginx }
#    - { role: monitoring }
