---

- hosts: localhost
#  remote_user: root
  sudo: yes
  # become_user: root
  gather_facts: false
  roles:
    - { role: sudoers }
    - { role: java }
    - { role: nginx }
#   - { role: nginx-ssl }
    - { role: tomcat }
#    - { role: mysql}
    - { role: java_app_deploy }


